version: '3.9'

services:
  # web-app:
  #   image: python

  db:
    image: postgres:alpine
    # restart: always
    container_name: db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./db/db-init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 15s

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "18080:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "./backend/:/usr/src/backend/"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
      - key=${key}
      - DEFAULT_USER=${DB_USER}
      - DEFAULT_PASS=${DB_PASS}

volumes:
  db-data: